### PR TITLE
week4

### PR DESCRIPTION
**Pull request by hjolie**
黃詩雯
http://35.92.135.68:8000/
http://35.92.135.68:8000/attraction/10

### CODE REVIEW

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by cwpeng** [comment]
You should merge pull request right after review approval.

**Comment by hjolie** [comment]
Sorry I forgot to merge the old one first > <
I'm trying to see how I can cancel the new commits.

**Comment by cwpeng** [comment]
Just merge it. Let bygones be bygones.

**Pull request merged**
